# Generated by Django 4.2 on 2025-06-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0002_privatechatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateChatRoom',
        ),
    ]
